name: "Run Tests - Laravel 8"

on:
    push:
        branches: [ v4.x ]

    pull_request:
        branches: [ v4.x ]

jobs:
  tests:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [8.1]
        laravel: [10.*]
        include:
          - laravel: 10.*
            testbench: 8.0

    name: P${{ matrix.php }} - L${{ matrix.laravel }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: pdo, sqlite, pdo_sqlite

    - name: Install Dependencies
      run: composer install

    - name: Execute tests
      run: vendor/bin/phpunit
