name: "Run Tests - Laravel 11"

on:
  push:
    branches: [ v7.x, master ]

  pull_request:
    branches: [ v7.x, master ]

jobs:
  tests:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ 8.2, 8.3 ]
        laravel: [ 11.* ]
        include:
          - laravel: 11.*
            testbench: 8.*

    name: P${{ matrix.php }} - L${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: pdo, sqlite, pdo_sqlite

      - name: Install Dependencies
        run: composer install

      - name: Execute tests
        run: vendor/bin/phpunit
