name: "Run Tests - Laravel 7"

on:
    push:
        branches: [ v3.x ]

    pull_request:
        branches: [ v3.x ]

jobs:
  tests:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [7.2, 7.3, 7.4, 8.0]
        laravel: [7.*]
        include:
          - laravel: 7.*
            testbench: 5

    name: P${{ matrix.php }} - L${{ matrix.laravel }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: pdo, sqlite, pdo_sqlite

    - name: Install Dependencies
      run: composer install

    - name: Execute tests
      run: vendor/bin/phpunit
