name: "Run Tests - Laravel 9"

on:
    push:
        branches: [ v5.x ]

    pull_request:
        branches: [ v5.x ]

jobs:
  tests:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [8.0]
        laravel: [9.*]
        include:
          - laravel: 9.*
            testbench: 7.*

    name: P${{ matrix.php }} - L${{ matrix.laravel }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: pdo, sqlite, pdo_sqlite

    - name: Install Dependencies
      run: composer install

    - name: Execute tests
      run: vendor/bin/phpunit
